### PR TITLE
Re-instate journey pattern links

### PR DESCRIPTION
**Pull request by tfk-kaare**

### CODE REVIEW

**Review by tft-abel — APPROVED** [review]

**Review by tft-kyrre — COMMENTED** [review]
No CHANGELOG.md entry?

**Comment by tfk-kaare** [comment]
No, this was a regression from pre netex route data import refactoring with christmastreeparser.

**Comment by tft-kyrre** [comment]
OK.

**Review by tft-kyrre — APPROVED** [review]

**Comment by tfk-kaare** [comment]
Squashed to master.

**Pull request closed without merging**
